AWSTemplateFormatVersion: '2010-09-09'
Description: 'TeachAssist Multi-Agent Application - SSM Parameter Store Configuration'

Parameters:
  AWSRegion:
    Type: String
    Default: us-east-1
    Description: AWS region for all services
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-west-1
      - ap-southeast-1

  BedrockModelId:
    Type: String
    Default: us.amazon.nova-2-lite-v1:0
    Description: Bedrock model ID or cross-region inference profile
    AllowedValues:
      - us.amazon.nova-2-lite-v1:0
      - us.amazon.nova-pro-v1:0
      - us.anthropic.claude-haiku-4-5-20251001-v1:0
      - us.anthropic.claude-sonnet-4-5-20250929-v1:0

  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod

  MaxResults:
    Type: Number
    Default: 9
    Description: Maximum results for knowledge base queries
    MinValue: 1
    MaxValue: 100

  MinScore:
    Type: Number
    Default: 0.000001
    Description: Minimum score threshold for knowledge base queries (0.0 to 1.0)
    MinValue: 0
    MaxValue: 1

  SageMakerInferenceComponent:
    Type: String
    Default: adapter-my-gpt-oss-20b-1-1768544341-1768544347
    Description: SageMaker inference component name (optional, for multi-model endpoints)

  SageMakerModelEndpoint:
    Type: String
    Default: my-gpt-oss-20b-1-1768544341
    Description: SageMaker model endpoint name (required when user selects SageMaker model)

  StrandsKnowledgeBaseId:
    Type: String
    Default: IMW46CITZE
    Description: Strands knowledge base ID for memory operations

  Temperature:
    Type: Number
    Default: 0.3
    Description: Model temperature setting for all agents (0.0 to 1.0)
    MinValue: 0
    MaxValue: 1

  XGBoostEndpointName:
    Type: String
    Default: xgboost-serverless-ep2026-01-12-05-31-16
    Description: XGBoost loan prediction endpoint name (required for loan assistant)

Resources:
  # AWS Region Parameter
  ParamAWSRegion:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/aws/region'
      Description: AWS region for all services
      Type: String
      Value: !Ref AWSRegion
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # Bedrock Model ID Parameter
  ParamBedrockModelId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/bedrock/model_id'
      Description: Bedrock model ID or cross-region inference profile
      Type: String
      Value: !Ref BedrockModelId
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # Max Results Parameter
  ParamMaxResults:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/knowledge_base/max_results'
      Description: Maximum results for knowledge base queries
      Type: String
      Value: !Ref MaxResults
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # Min Score Parameter
  ParamMinScore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/knowledge_base/min_score'
      Description: Minimum score threshold for knowledge base queries
      Type: String
      Value: !Ref MinScore
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # SageMaker Inference Component Parameter
  ParamSageMakerInferenceComponent:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/sagemaker/inference_component'
      Description: SageMaker inference component name
      Type: String
      Value: !Ref SageMakerInferenceComponent
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # SageMaker Model Endpoint Parameter
  ParamSageMakerModelEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/sagemaker/model_endpoint'
      Description: SageMaker model endpoint name
      Type: String
      Value: !Ref SageMakerModelEndpoint
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # Strands Knowledge Base ID Parameter
  ParamStrandsKnowledgeBaseId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/strands/knowledge_base_id'
      Description: Strands knowledge base ID for memory operations
      Type: String
      Value: !Ref StrandsKnowledgeBaseId
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # Temperature Parameter
  ParamTemperature:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/model/temperature'
      Description: Model temperature setting for all agents
      Type: String
      Value: !Ref Temperature
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

  # XGBoost Endpoint Name Parameter
  ParamXGBoostEndpointName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/teachassist/${Environment}/xgboost/endpoint_name'
      Description: XGBoost loan prediction endpoint name
      Type: String
      Value: !Ref XGBoostEndpointName
      Tags:
        Environment: !Ref Environment
        Application: TeachAssist
        ManagedBy: CloudFormation

Outputs:
  AWSRegionParameter:
    Description: SSM Parameter name for AWS Region
    Value: !Ref ParamAWSRegion

  BedrockModelIdParameter:
    Description: SSM Parameter name for Bedrock Model ID
    Value: !Ref ParamBedrockModelId

  MaxResultsParameter:
    Description: SSM Parameter name for Max Results
    Value: !Ref ParamMaxResults

  MinScoreParameter:
    Description: SSM Parameter name for Min Score
    Value: !Ref ParamMinScore

  ParameterPrefix:
    Description: SSM Parameter Store prefix for this environment
    Value: !Sub '/teachassist/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ParameterPrefix'

  SageMakerInferenceComponentParameter:
    Description: SSM Parameter name for SageMaker Inference Component
    Value: !Ref ParamSageMakerInferenceComponent

  SageMakerModelEndpointParameter:
    Description: SSM Parameter name for SageMaker Model Endpoint
    Value: !Ref ParamSageMakerModelEndpoint

  StrandsKnowledgeBaseIdParameter:
    Description: SSM Parameter name for Strands Knowledge Base ID
    Value: !Ref ParamStrandsKnowledgeBaseId

  TemperatureParameter:
    Description: SSM Parameter name for Model Temperature
    Value: !Ref ParamTemperature

  XGBoostEndpointNameParameter:
    Description: SSM Parameter name for XGBoost Endpoint
    Value: !Ref ParamXGBoostEndpointName
